receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  otlp/openobserve:
    endpoint: 192.168.1.229:5081
    headers:
      Authorization: "Basic ZGlwZXNoLnN1ZGVyc2hhbkBnbWFpbC5jb206M3gxRklLclpac0cwbEcycw=="
      organization: default
      stream-name: default
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]